import assert from 'node:assert/strict';
import * as THREE from 'three';
import {intersectUnit,stitchSectionSegments,projectDrills,intersectBlocks,sectionDefinitions,sectionWorld,planeDistance,sampleSectionTerrain,sampleSectionPits,type SectionDefinition,type SectionSource} from '../src/lib/deck/cross-section';
import {rectangle,inside} from '../src/lib/deck/site-planning';

const section:SectionDefinition={id:'test',title:'Test',ends:['A','A′'],origin:[0,0],along:[1,0],min:-100,max:100,azimuth:90};
const cube=new THREE.BoxGeometry(20,30,40);
const result=intersectUnit(cube,section);
assert.equal(result.loops.length,1,'Closed cube produces one fill');
assert.equal(result.open.length,0,'No invented open boundaries');
const loop=result.loops[0];
const area=Math.abs(loop.reduce((sum,p,i)=>{const q=loop[(i+1)%loop.length];return sum+p[0]*q[1]-q[0]*p[1];},0))/2;
assert.ok(Math.abs(area-600)<.01,'Exact 20 x 30 m plane intersection area');
assert.equal(Math.min(...loop.map(p=>p[1])),685,'Restores supplied elevation datum');
const open=stitchSectionSegments([[[0,0],[1,0]],[[1,0],[1,1]]]);assert.equal(open.loops.length,0);assert.equal(open.open.length,2);
const branched=stitchSectionSegments([[[0,0],[1,0]],[[1,0],[1,1]],[[1,1],[0,0]],[[1,0],[2,0]]]);assert.equal(branched.loops.length,0,'Non-manifold component is not filled');
const duplicates=stitchSectionSegments([[[0,0],[1,0]],[[1,0],[1,1]],[[1,1],[0,0]],[[1,0],[0,0]]]);assert.equal(duplicates.loops.length,1,'Duplicate segment is removed');
const drilled={holeId:'H1',from:[0,20,-100] as [number,number,number],to:[0,-20,100] as [number,number,number],carbon:4.2,depthFrom:0,depthTo:204};
const projected=projectDrills([drilled],section,25);
assert.equal(projected.length,1,'Both endpoints outside but interval crosses slab');
assert.deepEqual(projected[0].line,[[0,705],[0,695]],'Clips crossing interval to +/-25 m slab');
assert.equal(projectDrills([{...drilled,from:[0,20,40],to:[0,-20,40]}],section,25).length,0,'Parallel outside interval excluded');
const cells=intersectBlocks([{x:0,y:0,z:0,dx:20,dy:40,dz:30,carbon:4.2}],section);
assert.deepEqual(projectDrills([{...drilled,from:[-200,20,0],to:[200,-20,0]}],section,25)[0].line,[[-100,710],[100,690]],'Drills clipped to longitudinal bounds');
assert.equal(projectDrills([{...drilled,from:[NaN,0,0]}],section,25).length,0,'Nonfinite drill rejected');
assert.equal(stitchSectionSegments([[[0,0],[3,3]],[[3,3],[0,3]],[[0,3],[2,0]],[[2,0],[0,0]]]).loops.length,0,'Self-crossing ring not filled');
assert.equal(stitchSectionSegments([[[0,0],[1.004,0]],[[1.006,0],[1,1]],[[1,1],[0,0]]]).loops.length,1,'Adjacent hash buckets weld within tolerance');
assert.deepEqual(cells,[{min:-10,max:10,low:685,high:715,carbon:4.2}]);
assert.equal(intersectBlocks([{x:0,y:0,z:100,dx:20,dy:40,dz:30,carbon:4.2}],section).length,0,'Nearby but nonintersecting block is excluded');
const diagonal={...section,along:[Math.SQRT1_2,Math.SQRT1_2] as [number,number]};
assert.ok(Math.abs(intersectBlocks([{x:0,y:0,z:0,dx:20,dy:40,dz:30,carbon:4}],diagonal)[0].max-10*Math.SQRT2)<1e-8);
const longBox=new THREE.BoxGeometry(40,30,200);
const source:SectionSource={units:[{name:'GRSC',color:'#c7551b',geometry:longBox}],drills:[],blocks:[],pits:[{ring:rectangle([0,50],50,60),centre:[0,50],surface:20,floor:-10,depth:30,support:1},{ring:rectangle([0,-50],50,60),centre:[0,-50],surface:20,floor:-10,depth:30,support:1}],boundary:rectangle([0,0],300,400),height:()=>20};
const definitions=sectionDefinitions(source);
assert.equal(definitions.length,3);
assert.equal(definitions[0].origin[1],-50,'North/South derived spatially, not array order');
assert.ok(Math.abs(definitions[0].along[0])>.99,'Transverse across long model axis');
assert.ok(Math.abs(definitions[2].along[1])>.99,'Longitudinal follows geometric axis');
for(const d of definitions)for(const u of [d.min,(d.min+d.max)/2,d.max]){const p=sectionWorld(d,u);assert.ok(inside(p,source.boundary));assert.ok(Math.abs(planeDistance(p,d))<1e-8);}
assert.ok(sampleSectionTerrain(source,definitions[0]).every(p=>p[1]===720));
assert.ok(sampleSectionPits(source,definitions[0]).flat().every(p=>p[1]<=720));
console.log('PASS: closed fills, exact areas/datum, ambiguous outlines, duplicate removal, crossing slab clipping, exact block intersections, N/S model-axis definitions and matching locator');
